### ISSUE TITLE
Offer dockerNode config helper from this library

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud-libraries/nextcloud-cypress#97]
Most up to date is here:
https://github.com/nextcloud/viewer/blob/c089f77064a552624c3d41187dda6224f3015274/cypress/dockerNode.ts

Ideally we should have one that also works here without changes.
The only diff seems to be if we mount the app or not 
https://github.com/nextcloud/viewer/blob/c089f77064a552624c3d41187dda6224f3015274/cypress/dockerNode.ts#L30-L32
https://github.com/nextcloud/viewer/blob/c089f77064a552624c3d41187dda6224f3015274/cypress/dockerNode.ts#L80-L82

Surely we could just check if this is an app and read the info.xml straight away and ignore the volume if non existent? :thinking: 

cc @juliushaertl @max-nextcloud 

## References
- https://github.com/nextcloud/viewer/blob/master/cypress/dockerNode.ts
- https://github.com/nextcloud/nextcloud-cypress/blob/master/cypress/dockerNode.ts

**Comment by max-nextcloud** [comment]
I have not looked into docker integration with cypress yet. So far i'm just spinning up my `nextcloud-docker-dev` env and then point cypress to it with 
```bash
export CYPRESS_baseUrl=https://nextcloud.local/index.php
```

I'm looking forward to learn more about this but thus far i don't have much to contribute to the discussion.

**Comment by juliushaertl** [comment]
I'm using the same approach as Max locally, but the docker testing might still be nice to have an easy way to run the exact same baseline on CI and locally. Further this would also allow to drastically cleanup our GitHub action in text.

> Surely we could just check if this is an app and read the info.xml straight away and ignore the volume if non existent? 🤔

I'm wondering if we cannot just pass potential mappings as an argument as for text for example we also need to mount viewer as an additional app.

**Comment by skjnldsv** [comment]
So, uses cases are:
- Different server versions (master, stablexx...)
- App mount (from the same repo cypress is being run)
- Another external app mount (like needing viewer from text) ?

@juliushaertl can you confirm you actually need the last point?
Anything else I might have missed?

**Comment by juliushaertl** [comment]
Seems reasonable for the use cases we have.

One additional improvement might be to enable memory caching on the docker image as that brought a bit of performance improvements during the tests as well. In text we run `          php occ config:system:set memcache.local --value="\\OC\\Memcache\\APCu"` for that and the dockerfile [already has the module](https://github.com/nextcloud/docker-ci/blob/master/shallow-server/Dockerfile#L13)

**Comment by juliushaertl** [comment]
Note that the last point may also be helpful for other scenarios (e.g. collectives that installs circles for e2e tests)

**Comment by skjnldsv** [comment]
Yeah, ideally we could improve the shallow server too to allow specifying an array of shipped apps to be installed too.
Because doing this from the github actions will most likely be error-prone.

Regarding the configs, even during test you can manipulate the docker instance, so tuning it live for your desires :)
